import { forwardRef } from "react";
import { Pill, AlertTriangle, Clock, Activity, Shield, Utensils, FileText, Info } from "lucide-react";
import type { Medicine } from "@/data/medicineDatabase";

interface MedicineResult {
  medicine: Medicine;
  extractedDosage?: string;
  extractedFrequency?: string;
  extractedDuration?: string;
  confidence: number;
}

interface AIExtractedMedicine {
  name: string;
  dosage: string;
  frequency: string;
  duration: string;
  confidence: number;
}

interface PrescriptionReportProps {
  medicineResults: MedicineResult[];
  aiMedicines: AIExtractedMedicine[];
  rawText: string;
  scanDate: string;
}

export const PrescriptionReport = forwardRef<HTMLDivElement, PrescriptionReportProps>(
  ({ medicineResults, aiMedicines, rawText, scanDate }, ref) => {
    const unmatchedMedicines = aiMedicines.filter(
      m => !medicineResults.find(r => r.medicine.name.toLowerCase() === m.name.toLowerCase())
    );

    return (
      <div ref={ref} className="bg-white text-gray-900 p-8 max-w-4xl mx-auto font-sans">
        {/* Report Header */}
        <div className="border-b-2 border-blue-600 pb-6 mb-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-blue-600 rounded-xl flex items-center justify-center">
                <Pill className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-blue-700">MediScan AI</h1>
                <p className="text-sm text-gray-500">Prescription Analysis Report</p>
              </div>
            </div>
            <div className="text-right text-sm text-gray-500">
              <p className="font-medium text-gray-700">Report Date</p>
              <p>{scanDate}</p>
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="bg-yellow-50 border border-yellow-300 rounded-lg p-4 mb-6">
          <p className="text-xs text-yellow-800 font-medium">
            ⚠️ MEDICAL DISCLAIMER: This report is generated by AI and is intended for informational purposes only.
            It does NOT replace professional medical advice, diagnosis, or treatment. Always follow your doctor's
            instructions and consult a licensed healthcare professional before making any medical decisions.
          </p>
        </div>

        {/* Summary */}
        <div className="bg-blue-50 rounded-xl p-5 mb-6">
          <h2 className="text-lg font-bold text-blue-800 mb-3 flex items-center gap-2">
            <FileText className="w-5 h-5" /> Prescription Summary
          </h2>
          <div className="grid grid-cols-3 gap-4 text-center">
            <div className="bg-white rounded-lg p-3 shadow-sm">
              <div className="text-2xl font-bold text-blue-600">{aiMedicines.length}</div>
              <div className="text-xs text-gray-500 mt-1">Medicines Found</div>
            </div>
            <div className="bg-white rounded-lg p-3 shadow-sm">
              <div className="text-2xl font-bold text-green-600">{medicineResults.length}</div>
              <div className="text-xs text-gray-500 mt-1">Database Matches</div>
            </div>
            <div className="bg-white rounded-lg p-3 shadow-sm">
              <div className="text-2xl font-bold text-orange-500">
                {aiMedicines.length > 0
                  ? Math.round(aiMedicines.reduce((a, m) => a + m.confidence, 0) / aiMedicines.length)
                  : 0}%
              </div>
              <div className="text-xs text-gray-500 mt-1">Avg. Confidence</div>
            </div>
          </div>
        </div>

        {/* Extracted Text */}
        {rawText && (
          <div className="mb-6">
            <h2 className="text-lg font-bold text-gray-800 mb-3 flex items-center gap-2">
              <FileText className="w-5 h-5 text-gray-600" /> Raw Extracted Text
            </h2>
            <div className="bg-gray-50 border rounded-lg p-4 font-mono text-sm text-gray-700 whitespace-pre-wrap">
              {rawText}
            </div>
          </div>
        )}

        {/* Detailed Medicine Cards */}
        {medicineResults.length > 0 && (
          <div className="mb-6">
            <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
              <Pill className="w-5 h-5 text-blue-600" /> Detailed Medicine Information
            </h2>

            {medicineResults.map((result, idx) => (
              <div key={idx} className="border-2 border-gray-200 rounded-xl mb-6 overflow-hidden">
                {/* Medicine Header */}
                <div className="bg-blue-600 text-white p-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <h3 className="text-xl font-bold">{result.medicine.name}</h3>
                      <p className="text-blue-100 text-sm">{result.medicine.genericName}</p>
                    </div>
                    <div className="text-right">
                      <div className="text-xs text-blue-200">Confidence</div>
                      <div className="text-xl font-bold">{result.confidence}%</div>
                    </div>
                  </div>
                  <span className="inline-block mt-2 px-3 py-1 text-xs font-medium bg-blue-500 rounded-full">
                    {result.medicine.category}
                  </span>
                </div>

                <div className="p-4 space-y-4">
                  {/* Prescription Info */}
                  <div className="grid grid-cols-4 gap-3">
                    <div className="bg-gray-50 rounded-lg p-3 text-center">
                      <Activity className="w-4 h-4 text-blue-500 mx-auto mb-1" />
                      <div className="text-xs text-gray-500">Treats</div>
                      <div className="text-sm font-semibold truncate">{result.medicine.diseases[0]}</div>
                    </div>
                    <div className="bg-gray-50 rounded-lg p-3 text-center">
                      <Clock className="w-4 h-4 text-blue-500 mx-auto mb-1" />
                      <div className="text-xs text-gray-500">Dosage</div>
                      <div className="text-sm font-semibold">{result.extractedDosage || result.medicine.commonDosage.split(" ")[0]}</div>
                    </div>
                    <div className="bg-gray-50 rounded-lg p-3 text-center">
                      <Utensils className="w-4 h-4 text-blue-500 mx-auto mb-1" />
                      <div className="text-xs text-gray-500">Form</div>
                      <div className="text-sm font-semibold">{result.medicine.dosageForm.split("/")[0]}</div>
                    </div>
                    <div className="bg-gray-50 rounded-lg p-3 text-center">
                      <Info className="w-4 h-4 text-blue-500 mx-auto mb-1" />
                      <div className="text-xs text-gray-500">Frequency</div>
                      <div className="text-sm font-semibold">{result.extractedFrequency || "As prescribed"}</div>
                    </div>
                  </div>

                  {/* How to Take */}
                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                    <h4 className="font-semibold text-blue-800 flex items-center gap-2 mb-2">
                      <Utensils className="w-4 h-4" /> How to Take
                    </h4>
                    <p className="text-sm text-gray-700">{result.medicine.intakeGuidelines}</p>
                  </div>

                  {/* Side Effects & Overdose in 2 columns */}
                  <div className="grid grid-cols-2 gap-4">
                    {/* Common Side Effects */}
                    <div className="bg-amber-50 border border-amber-300 rounded-lg p-4">
                      <h4 className="font-semibold text-amber-800 flex items-center gap-2 mb-2">
                        <AlertTriangle className="w-4 h-4" /> Common Side Effects
                      </h4>
                      <ul className="text-sm text-gray-700 space-y-1">
                        {result.medicine.sideEffects.map((effect, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-1.5 shrink-0" />
                            {effect}
                          </li>
                        ))}
                      </ul>
                    </div>

                    {/* Overdose Effects */}
                    <div className="bg-red-50 border border-red-300 rounded-lg p-4">
                      <h4 className="font-semibold text-red-700 flex items-center gap-2 mb-2">
                        <AlertTriangle className="w-4 h-4" /> Overdose / Overuse Effects
                      </h4>
                      <ul className="text-sm text-gray-700 space-y-1">
                        {result.medicine.overuseEffects.map((effect, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-1.5 shrink-0" />
                            {effect}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Conditions Treated */}
                  <div>
                    <h4 className="font-semibold text-gray-700 flex items-center gap-2 mb-2">
                      <Activity className="w-4 h-4 text-blue-500" /> Conditions Treated
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {result.medicine.diseases.map((disease, i) => (
                        <span key={i} className="px-3 py-1 text-xs bg-blue-100 text-blue-700 rounded-full">
                          {disease}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Warnings */}
                  <div>
                    <h4 className="font-semibold text-gray-700 flex items-center gap-2 mb-2">
                      <Shield className="w-4 h-4 text-blue-500" /> Warnings & Precautions
                    </h4>
                    <ul className="text-sm text-gray-600 space-y-1">
                      {[...result.medicine.warnings, ...result.medicine.precautions].map((item, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="w-1.5 h-1.5 rounded-full bg-blue-400 mt-1.5 shrink-0" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Unmatched medicines */}
        {unmatchedMedicines.length > 0 && (
          <div className="mb-6">
            <h2 className="text-lg font-bold text-gray-800 mb-3">Additional Medicines (AI Detected)</h2>
            <div className="space-y-3">
              {unmatchedMedicines.map((med, i) => (
                <div key={i} className="border rounded-lg p-4 flex items-center justify-between bg-gray-50">
                  <div>
                    <p className="font-semibold text-gray-800">{med.name}</p>
                    <p className="text-sm text-gray-500">
                      {[med.dosage, med.frequency, med.duration].filter(Boolean).join(" • ")}
                    </p>
                  </div>
                  <span className="text-sm text-gray-400">{med.confidence}% confidence</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="border-t-2 border-gray-200 pt-4 mt-6 text-center text-xs text-gray-400">
          <p>Generated by MediScan AI • {scanDate} • For informational purposes only</p>
          <p className="mt-1">Always consult a licensed healthcare professional for medical advice.</p>
        </div>
      </div>
    );
  }
);

PrescriptionReport.displayName = "PrescriptionReport";
